#!/bin/sh
#
# boilercontrol          This shell script takes care of starting and stopping the boiler controller.
#
# chkconfig: 35 61 40
# description: Control boiler via an RS485 bus
#

. /etc/rc.d/init.d/functions

PATH=/usr/sbin:/bin:/usr/bin:/sbin
BOILERCONTROL=/usr/local/bin/boiler_controller.rb
PIDDIR=/var/run/boiler_controller
PIDFILE=$PIDDIR/boiler_controller.pid
LOGFILE=/var/log/boiler_controller/boiler_service.log
ERRORLOGFILE=/var/log/boiler_controller/boiler_error.log

if [ ! -x "$BOILERCONTROL" ]; then
  echo -n $"No executable found, exiting"
  failure
  echo
  exit 1
fi
 
case "$1" in
   start)
     echo -n $"Starting boilercontrol:"
     rm -f $PIDFILE
     if [ ! -d "$PIDDIR" ]; then
	mkdir $PIDDIR
     fi
     chown root.boiler $PIDDIR
     chmod g+rwx $PIDDIR
     export GEM_PATH=/usr/local/rvm/gems/ruby-2.1.5:/usr/local/rvm/gems/ruby-2.1.5@global
     daemon --user boiler -3 "$BOILERCONTROL --daemon --pidfile $PIDFILE >>$LOGFILE 2>>$ERRORLOGFILE"
     echo
     exit 0
     ;;
   stop)
     echo -n "Stopping boilercontrol:"
     killproc -p $PIDFILE -d 60 $BOILERCONTROL
     echo
     exit 0
     ;;
   debugstart)
     sh $0 start
     sh $0 applog
     ;;
   restart)
     sh $0 stop
     sleep 2
     sh $0 start
     ;;
   status)
	 status -p $PIDFILE $BOILERCONTROL
   	 ;;
   heatlog)
     echo -n "Turning on heating logging"
     killproc $BOILERCONTROL -USR1
     echo
     ;;
   applog)
     echo -n "Turning on application logging"
     killproc $BOILERCONTROL -URG
     echo
     ;;
   logoff)
     echo -n "Turning off all logging"
     killproc $BOILERCONTROL -USR2
     echo
     ;;
   *)
     echo "Usage: boilercontrol {start|stop|debugstart|restart|status|logoff|applog|heatlog}"
     exit 3
     ;;
esac
 
exit 0
