#!/bin/sh

FURNACE_RESTART_NEEDED=0
#OWFS_RESTART_NEEDED=0
OWSERVER_RESTART_NEEDED=0

if [ -z "$(/etc/init.d/furnacecontrol status | grep  "is running...")" ]; then
    echo No furnacecontrol process running
    FURNACE_RESTART_NEEDED=1
fi

#if [ -z "$(ps -e | grep  owfs)" ]; then
#    echo No owfs process running
#    OWFS_RESTART_NEEDED=1
#    FURNACE_RESTART_NEEDED=1
#fi

#if [ -z "$(mount | grep  1wire)" ]; then
#    echo 1wire filesystem not in mtab
#    OWFS_RESTART_NEEDED=1
#    FURNACE_RESTART_NEEDED=1
#fi

#if [ ! -d /mnt/1wire/05.EFF131000000 ]; then
#    echo No directory found for "05.EFF131000000"
#    OWFS_RESTART_NEEDED=1
#    FURNACE_RESTART_NEEDED=1
#fi

if [ -z "$(/etc/init.d/owserver status | grep  "is running...")" ]; then
    echo No owserver process running
    OWSERVER_RESTART_NEEDED=1
    OWFS_RESTART_NEEDED=1
    FURNACE_RESTART_NEEDED=1
fi


if [ "$FURNACE_RESTART_NEEDED" -eq 1 ] || [ "$OWSERVER_RESTART_NEEDED" -eq 1 ]; then
    echo
    echo Execting cleanups
    echo
fi

# Stop or cleanup what is not found
if [ "$FURNACE_RESTART_NEEDED" -eq 1 ]; then
    echo Doing furnace cleanup
    /etc/init.d/furnacecontrol stop
    killall furnacecontrol.rb
    sleep 1
    killall -9 furnacecontrol.rb
    echo
fi

#if [ "$OWFS_RESTART_NEEDED" -eq 1 ]; then
#    echo Doing owfs cleanup
#    /etc/init.d/owfs stop
#    killall owfs
#    killall -9 owfs
#    echo
#fi

if [ "$OWSERVER_RESTART_NEEDED" -eq 1 ]; then
    echo Doing owserver cleanup
    /etc/init.d/owserver stop
    killall owserver
    sleep 1
    killall -9 owserver
    echo
fi

# Restart what was cleaned up

if [ "$OWSERVER_RESTART_NEEDED" -eq 1 ]; then
    echo
    echo Starting owserver
    /etc/init.d/owserver start 
#    echo Starting owfs
#    /etc/init.d/owfs start 
    echo Starting furnace control
    sleep 1
    /etc/init.d/furnacecontrol start
    exit
fi

#if [ "$OWFS_RESTART_NEEDED" -eq 1 ]; then
#    echo
#    echo Starting owfs
#    /etc/init.d/owfs start
#    echo Starting furnace control
#    sleep 1
#    /etc/init.d/furnacecontrol start
#    exit
#fi

if [ "$FURNACE_RESTART_NEEDED" -eq 1 ]; then
    echo
    echo Starting furnace control
    sleep 1
    /etc/init.d/furnacecontrol start
    exit
fi

exit