#!/bin/sh
#
# owserver          This shell script takes care of starting and stopping the owserver 1wire server
#
# chkconfig: 35 59 42
# description: OWSERVER
#


# Source function library.
. /etc/rc.d/init.d/functions

PATH=/usr/sbin:/bin:/usr/bin:/sbin
OWSERVER=/opt/owfs/bin/owserver
 
# Arguments
#
OWSERVERPIDFILE="/var/run/owserver.pid"

OWSERVERARGS="-u -p 4304 --timeout_volatile=0 -P $OWSERVERPIDFILE &>/dev/null"


case "$1" in
   start)
     echo  -n $"Starting owserver:"
     rm -f $OWSERVERPIDFILE
     daemon "$OWSERVER $OWSERVERARGS"
     echo
     exit 0
     ;;
   stop)
     echo -n $"Stopping owserver:"
     killproc -p $OWSERVERPIDFILE $OWSERVER
     echo
     exit 0
     ;;
   status)
   	 status -p $OWSERVERPIDFILE $OWSERVER 
   	 ;;
   restart)
     sh $0 stop
     sh $0 start
     exit 0
     ;;
   *)
     echo "Usage: owserver {start|stop|status|restart}"
     exit 3
     ;;
esac
 
exit 0