#!/bin/sh
#
# furnacecontrol          This shell script takes care of starting and stopping the furnace controller.
#
# chkconfig: 35 61 40
# description: Control furnace via one wire filesystem
#

. /etc/rc.d/init.d/functions

PATH=/usr/sbin:/bin:/usr/bin:/sbin
FURNACECONTROL=/usr/local/bin/furnacecontrol.rb
PIDFILE=/var/run/furnacecontrol.pid

if [ ! -x "$FURNACECONTROL" ]; then
  echo -n $"No executable found, exiting"
  failure
  echo
  exit 1
fi
 
case "$1" in
   start)
     echo -n $"Starting furnacecontrol:"
     rm -f $PIDFILE
     daemon "$FURNACECONTROL &>/dev/null"
     echo
     exit 0
     ;;
   stop)
     echo -n "Stopping furnacecontrol:"
     killproc -p $PIDFILE -d 3 $FURNACECONTROL
     echo
     exit 0
     ;;
   restart)
     sh $0 stop
     sleep 1
     sh $0 start
     ;;
   status)
	 status -p $PIDFILE $FURNACECONTROL
   	 ;;
   normlog)
     echo -n "Turning on normal logging"
     killproc $FURNACECONTROL -USR1
     echo
     ;;
   controllog)
     echo -n "Turning on control logging"
     killproc $FURNACECONTROL -URG
     echo
     ;;
   logoff)
     echo -n "Turning off all logging"
     killproc $FURNACECONTROL -USR2
     echo
     ;;
   *)
     echo "Usage: furnacecontrol {start|stop|restart|status|logoff|normlog|controllog}"
     exit 3
     ;;
esac
 
exit 0
